image: node:latest
variables:
# Use clang compiler
  CC: "clang"
  CXX: "clang++"
before_script:
  - npm set registry http://sinopia.linkedsoftwaredependencies.org
# Install clang compiler
  - apt-get update
  - apt-get install -y clang
# Install CMake
  - curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC /opt
  - export PATH="/opt/cmake-3.5.2-Linux-x86_64/bin/:$PATH"
# Install Kyoto Cabinet
  - ./install-kc-ci.sh
# Install module dependencies
  - npm install --unsafe-perm

cache:
  key: "$CI_PROJECT_PATH/$CI_BUILD_REF_NAME/$NODE_VERSION"
  paths:
  - node_modules/

test_all:
  script:
   - npm test

test_lint:
  script:
   - npm run lint
