language: node_js
node_js:
 - "6"
 - "8"
 - "10"
 - "12"
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
